
# 7. Frontend Deployment
apiVersion: apps/v1
kind: {{ .Values.app_kind }}
metadata:
  name: {{ .Values.app_name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rolling_update_max_unavailable }}
      maxSurge: {{ .Values.rolling_update_max_surge }} 
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Values.app_name }}
          image: {{ .Values.cont_image }} 
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap_name }}
                  key: PORT
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap_name }}
                  key: API_HOST            
          # env:
          #   - name: PORT
          #     value: "3000"
          #   - name: API_HOST
          #     value: "http://4.236.40.1"  # Replace <external-ip> after deployment
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3      

 #az aks get-credentials --resource-group aks-rg --name myakscluster      run this command after terraform apply and infrastructure is created.
      # or  run before kubectl apply. This command will cerate kubeconfig file


