# 1. Secret for MySQL credentials
apiVersion: v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.secret_name }}
type: {{ .Values.sec_type }}
data:
  MYSQL_USER: a2FpemVu              # "kaizen"
  MYSQL_PASSWORD: a2FpemVuMTIzIQ==  # "kaizen123!"
  MYSQL_DATABASE: aGVsbG8=          # "hello"