
# 7. Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: buginets/node-js-web  # Replace with your image
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: API_HOST
              value: "http://4.236.40.1"  # Replace <external-ip> after deployment
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3      

 #az aks get-credentials --resource-group aks-rg --name myakscluster      run this command after terraform apply and infrastructure is created.
      # or  run before kubectl apply. This command will cerate kubeconfig file


