
# 6. Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_name }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
    - port: {{ .Values.svc_port }}
      targetPort: {{ .Values.svc_target_port }}
  type: {{ .Values.svc_type }} 

  
# # 2. Headless MySQL Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
# spec:
#   ports:
#     - port: 3306
#       targetPort: 3306
#       name: mysql
#   clusterIP: None
#   selector:
#     app: mysql

# ---

# # 4. Backend Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app-service
# spec:
#   selector:
#     app: my-app
#   ports:
#     - port: 80
#       targetPort: 8080
#   type: ClusterIP




