
   #database mysql file
   
depl_kind: StatefulSet
app_name: mysql
term_grace-prd_sec: 30
vlm_mnt_name: mysql-persistent-storage
vlm_mnt_path: /var/lib/mysql
mysql_img_tag: 5.7
storage_Class: "managed-csi"
storage_size: 1Gi

   #secret file
secret_file_name: mysql-secret
   
   
   #service file
service_name: mysql-service
mysql_svc_port: 3306
