apiVersion: apps/v1
kind: {{ .Values.depl_kind }}
metadata:
  name: {{ .Values.app_name }}
spec:
  serviceName: {{ .Values.service_name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.term_grace-prd_sec }}
      initContainers:
        - name: clean-mysql-dir
          image: alpine
          command: ["sh", "-c", "rm -rf /var/lib/mysql/*"]
          volumeMounts:
            - name: {{ .Values.vlm_mnt_name }}
              mountPath: {{ .Values.vlm_mnt_path }}
      containers:
        - name: {{ .Values.app_name }}
          image: {{ .Values.app_name }}:{{ .Values.mysql_img_tag }}
          ports:
            - containerPort: 3306
              name: {{ .Values.app_name }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_file_name }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_file_name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_file_name }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_file_name }}
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: {{ .Values.vlm_mnt_name }}
              mountPath: {{ .Values.vlm_mnt_path }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.vlm_mnt_name }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage_Class }}
        resources:
          requests:
            storage: {{ .Values.storage_size }}
